# Generated by Django 4.1.7 on 2023-03-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OscarWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directors', models.CharField(max_length=255, verbose_name='directors')),
                ('film_name', models.CharField(max_length=255, verbose_name='name')),
                ('nomination_winner', models.CharField(max_length=255, verbose_name='nomination_winner')),
            ],
        ),
    ]
