# Generated by Django 3.2.17 on 2023-03-02 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='contest_name')),
                ('rating_change', models.IntegerField(verbose_name='rating_change')),
                ('new_rating', models.IntegerField(verbose_name='new_rating')),
                ('title_change', models.CharField(max_length=255, verbose_name='title_change')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('rating', models.IntegerField(verbose_name='rating')),
                ('max_rating', models.IntegerField(verbose_name='max_rating')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
        ),
        migrations.DeleteModel(
            name='OscarWinner',
        ),
        migrations.AddField(
            model_name='contestresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='online_site.profile'),
        ),
    ]
