# Generated by Django 3.2.17 on 2023-03-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_site', '0002_auto_20230302_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='best_title',
            field=models.CharField(default='something', max_length=255, verbose_name='best_title'),
            preserve_default=False,
        ),
    ]
